# Generated by Django 4.2.16 on 2024-09-08 12:20

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk123456789', length=10, max_length=20, prefix='cat', unique=True)),
                ('title', models.CharField(choices=[('blush', 'Blush'), ('bronzer', 'Bronzer'), ('eyebrow', 'Eyebrow'), ('eyeliner', 'Eyeliner'), ('eyeshadow', 'Eyeshadow'), ('foundation', 'Foundation'), ('lip liner', 'Lip Liner'), ('lipstick', 'Lipstick'), ('mascara', 'Mascara'), ('nail polish', 'Nail Polish')])),
                ('image', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk123456789', length=10, max_length=20, prefix='pro', unique=True)),
                ('title', models.CharField(max_length=150)),
                ('product_type', models.CharField(max_length=150)),
                ('image', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(choices=[('almay', 'Almay'), ('alva', 'Alva'), ('anna sui', 'Anna Sui'), ('annabelle', 'Annabelle'), ('benefit', 'Benefit'), ('boosh', 'Boosh'), ("burt's bees", "Burt's Bees"), ('butter london', 'Butter London'), ("c'est moi", "C'est Moi"), ('cargo cosmetics', 'Cargo Cosmetics'), ('china glaze', 'China Glaze'), ('clinique', 'Clinique'), ('coastal classic creation', 'Coastal Classic Creation'), ('colourpop', 'Colourpop'), ('covergirl', 'Covergirl'), ('dalish', 'Dalish'), ('deciem', 'Deciem'), ('dior', 'Dior'), ('dr. hauschka', 'Dr. Hauschka'), ('e.l.f.', 'E.L.F.'), ('essie', 'Essie'), ('fenty', 'Fenty'), ('glossier', 'Glossier'), ('green people', 'Green People'), ('iman', 'Iman'), ("l'oreal", "L'Oreal"), ('lotus cosmetics usa', 'Lotus Cosmetics USA'), ("maia's mineral galaxy", "Maia's Mineral Galaxy"), ('marcelle', 'Marcelle'), ('marienatie', 'Marienatie'), ('maybelline', 'Maybelline'), ('milani', 'Milani'), ('mineral fusion', 'Mineral Fusion'), ('misa', 'Misa'), ('mistura', 'Mistura'), ('moov', 'Moov'), ('nudus', 'Nudus'), ('nyx', 'NYX'), ('orly', 'Orly'), ('pacifica', 'Pacifica'), ('penny lane organics', 'Penny Lane Organics'), ('physicians formula', 'Physicians Formula'), ('piggy paint', 'Piggy Paint'), ('pure anada', 'Pure Anada'), ('rejuva minerals', 'Rejuva Minerals'), ('revlon', 'Revlon'), ("sally b's skin yummies", "Sally B's Skin Yummies"), ('salon perfect', 'Salon Perfect'), ('sante', 'Sante'), ('sinful colours', 'Sinful Colours'), ('smashbox', 'Smashbox'), ('stila', 'Stila'), ('suncoat', 'Suncoat'), ('w3llpeople', 'W3LLPeople'), ('wet n wild', 'Wet n Wild'), ('zorah', 'Zorah'), ('zorah biocosmetiques', 'Zorah Biocosmetiques')])),
                ('featured', models.BooleanField(default=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_value', models.CharField(max_length=50)),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProudctEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk123456789', length=10, max_length=20, prefix='pro', unique=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('colorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.productcolors')),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.product')),
            ],
        ),
    ]
