# Generated by Django 4.2.16 on 2024-09-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_proudctentry_productentry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolors',
            options={'verbose_name_plural': 'Product Colors'},
        ),
        migrations.AlterModelOptions(
            name='productentry',
            options={'verbose_name_plural': 'Product Entries'},
        ),
        migrations.AlterField(
            model_name='productentry',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
