# Generated by Django 4.2.16 on 2024-09-08 12:54

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_productcolors_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolors',
            name='colorId',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk123456789', length=10, max_length=20, prefix='col', unique=True),
        ),
    ]
