# Generated by Django 4.2.16 on 2024-09-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_productcolors_colorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='colorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.productcolors'),
        ),
    ]
