# Generated by Django 4.2.16 on 2024-09-12 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_wishlistitem_wishlisit_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='productId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='main_app.product'),
        ),
    ]
