# Generated by Django 4.2.16 on 2024-09-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_productentry_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='productId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.product'),
        ),
    ]
